# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insider', models.CharField(max_length=50, verbose_name='Insider')),
                ('relation', models.CharField(max_length=20, verbose_name='Relation')),
                ('last_date', models.DateField(verbose_name='Last date')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='Transaction type')),
                ('owner_type', models.CharField(max_length=20, verbose_name='Owner type')),
                ('shares_traded', models.FloatField(verbose_name='Shares traded')),
                ('last_price', models.FloatField(verbose_name='Last price')),
                ('shares_held', models.FloatField(verbose_name='Shares held')),
            ],
            options={
                'verbose_name': 'insider trade',
                'verbose_name_plural': 'insider trades',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.PositiveIntegerField(verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('security_name', models.CharField(max_length=255, verbose_name='Security name')),
                ('market_category', models.CharField(max_length=5, verbose_name='Market category')),
                ('test_issue', models.CharField(max_length=5, verbose_name='Test Issue')),
                ('financial_status', models.CharField(max_length=5, verbose_name='Financial status')),
                ('round_lot_size', models.PositiveIntegerField(verbose_name='Round lot size')),
                ('etf', models.CharField(max_length=5, verbose_name='ETF')),
                ('next_shares', models.CharField(max_length=5, verbose_name='Next shares')),
            ],
            options={
                'verbose_name': 'ticker',
                'verbose_name_plural': 'tickers',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mainapp.Ticker', verbose_name='Ticker'),
        ),
        migrations.AddField(
            model_name='insidertrade',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_trades', to='mainapp.Ticker', verbose_name='Ticker'),
        ),
    ]
