# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertrade',
            name='shares_held',
            field=models.PositiveIntegerField(verbose_name='Shares held'),
        ),
        migrations.AlterField(
            model_name='insidertrade',
            name='shares_traded',
            field=models.PositiveIntegerField(verbose_name='Shares traded'),
        ),
    ]
