# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180405_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidertrade',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
